export const API_BASE_URL = 'http://localhost:8080/api';

export const QUERY_KEYS = {
  tenants: 'tenants',
  tenant: 'tenant',
  me: 'me',
  stores: 'stores',
  store: 'store',
  counters: 'counters',
  counter: 'counter',
  saStores: 'saStores',
  saStore: 'saStore',
  saCounters: 'saCounters',
  users: 'users',
  user: 'user',
  saUsers: 'saUsers',
  saUser: 'saUser',
  saCategories: 'saCategories',
  saCategory: 'saCategory',
  saProducts: 'saProducts',
  saProduct: 'saProduct',
  saCounter: 'saCounter',
  categories: 'categories',
  category: 'category',
  products: 'products',
  product: 'product',
  receipts: 'receipts',
  receipt: 'receipt',
  stock: 'stock',
  batches: 'batches',
  sales: 'sales',
  sale: 'sale',
  returns: 'returns',
  saleReturn: 'saleReturn',
} as const;

export const PAGE_SIZE_DEFAULT = 10;